import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import  Sidemenu  from "../components/layout/menu/sidemenu";
import { Layout } from "antd";
import { cookies } from "next/headers"; 
import AntdLayout from "@/components/layout/AntdLayout";
import { AntdRegistry } from '@ant-design/nextjs-registry';
const { Sider, Content, Header } = Layout;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "dev-insight",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get('token');

  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AntdRegistry>
            <AntdLayout hasToken={!!token}>
              {children}
            </AntdLayout>
        </AntdRegistry>
      </body>
    </html>
  );
}
